config/routes.rb
Eshop::Application.routes.draw do
  get "eshop/careers"

  get "eshop/about"

  get "eshop/help"

  get "eshop/contact"

  get "admin/index"

  get "admin/show"

  devise_for :admins

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end

  root :to => 'store#index', :as => 'store'

end

app/views/layouts/general/_footer.html.erb
<footer>
	<div id="copyright">
	  <div class="row full-width">
	    <div class="large-4 columns">
	      <p>&copy; 2013 eShop Systems ,Ltd.</p>
	    </div>
	    <div class="large-8 columns">
	      <ul class="inline-list right">
	        <li>
	        	<%= link_to('Work at eShop',  eshop_careers_path) %>
	        </li>
	        <li>
	        	<%= link_to('About Us', eshop_about_path) %>
	        </li>
	        <li>
	        	<%= link_to('Help', eshop_help_path) %>
	        </li>
	        <li>
	        	<%= link_to('Contact Us', eshop_contact_path) %>
	        </li>
	      </ul>
	    </div>
	  </div>
	</div>
</footer>

app/views/layouts/general/_header.html.erb
<header>
      <nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to "eShop Online Store", store_index_path %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      	
      	<li class="divider"></li>
      	<% if admin_signed_in? %>
      		<li>
      			<%= link_to('Admin Logout', destroy_admin_session_path, :method=>'delete') %>
      		</li>
			
		<%else%>
			<li>
				<%= link_to('Admin Login', admin_session_path) %>
			</li>
		<% end%>
      	
      	<% if admin_signed_in? %>
	      	<li class="has-dropdown"><a href="#">Products</a>
	
	        <ul class="dropdown">
	          <li>
	    		<%= link_to('View Products', products_path) %>
	    	  </li>

	          <li class="divider"></li>
	          
			  <li>
	    		<%= link_to('Create New', new_product_path) %>
	    	  </li>
	    	  
	    	  <li class="divider"></li>
	    	  
	        </ul>
	      </li>
	      
	      <!-- Menu for managing Orders-->
	      <li class="has-dropdown"><a href="#">Orders</a>
	
	        <ul class="dropdown">
	          <li>
	    		<%= link_to('View Orders', orders_path) %>
	    	  </li>

	          <li class="divider"></li>
	          
			  <li>
	    		<%= link_to('Create New', '#') %>
	    	  </li>
	    	  
	    	  <li class="divider"></li>
	    	  
	        </ul>
	      
	      <!-- Menu for managing users-->
	      <li class="has-dropdown"><a href="#">Users</a>
	
	        <ul class="dropdown">
	          <li>
	    		<%= link_to('Create New Admin', new_admin_registration_path) %>
	    	  </li>
	        	
	          <li>
	    		<%= link_to('Edit account', edit_admin_registration_path) %>
	    	  </li>
	    	  
	    	  <li>
	    		<%= link_to('View All Admins', admin_index_path) %>
	    	  </li>
	    	  
	          <li class="divider"></li>
	          
			  <li>
	    		<%= link_to('Admin Logout', destroy_admin_session_path, :method=>'delete') %>
	    	  </li>
	    	  
	    	  <li class="divider"></li>
	    	  
	        </ul>
	      </li>
        <% end %>
      	
      
      <li class="divider"></li>
     
    </ul>

	    <!-- Right Nav Section -->
	    <ul class="right">
	      <li class="divider hide-for-small"></li>
	  
	      <li class="has-form">
	        <form>
	          <div class="row collapse">
	            <div class="small-8 columns">
	              <input type="text" placeholder="Search eShop">
	            </div>
	            <div class="small-4 columns">
	              <a href="#" class="button">Search</a>
	            </div>
	          </div>
	        </form>
	      </li>
	      <li class="divider show-for-small"></li>
	      
	    </ul>
  </section>
</nav>
</header>

app/views/layouts/general/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert-box <%= name == :notice ? "success" : "alert" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>